"Resource/UI/NukeDetonation.res"
{
	"CountdownPanel"
	{
		"ControlName"	"CASW_VGUI_Countdown_Panel"
		"fieldName"		"CountdownPanel"
		"xpos"			"c-100"
		"ypos"			"40"
		"wide"			"200"
		"tall"			"80"
		"enabled"		"1"
		"visible"		"1"
	}
	
	"NukeBackground"
	{
		"ControlName"	"Panel"
		"fieldName"		"NukeBackground"
		"xpos"			"0"
		"ypos"			"0"
		"wide"			"200"
		"tall"			"80"
		"zpos"			"-1"
		"enabled"		"1"
		"PaintBackgroundType"	"2"
		"bgcolor_override"	"255 0 0 32"
	}
	
	"WarningLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"WarningLabel"
		"xpos"			"0"
		"ypos"			"10"
		"zpos"			"2"
		"wide"			"200"
		"tall"			"15"
		"enabled"		"1"
		"textAlignment"		"center"
		"font" "DefaultBold"
		"FgColor_override" "255 0 0 255"
		"bgcolor_override"	"0 0 0 0"
	}
	"WarningGlowLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"WarningGlowLabel"
		"xpos"			"0"
		"ypos"			"10"
		"zpos"			"1"
		"wide"			"200"
		"tall"			"15"
		"enabled"		"1"
		"textAlignment"		"center"
		"font" "DefaultBoldBlur"
		"FgColor_override" "255 0 0 255"
		"bgcolor_override"	"0 0 0 0"
	}
	"DetonationLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"DetonationLabel"
		"xpos"			"0"
		"ypos"			"30"
		"zpos"			"2"
		"wide"			"200"
		"tall"			"15"
		"enabled"		"1"
		"textAlignment"		"center"
		"font" "Default"
		"FgColor_override" "255 0 0 255"
		"bgcolor_override"	"0 0 0 0"
	}
	"DetonationGlowLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"DetonationGlowLabel"
		"xpos"			"0"
		"ypos"			"30"
		"zpos"			"1"
		"wide"			"200"
		"tall"			"15"
		"enabled"		"1"
		"textAlignment"		"center"
		"font" "DefaultBlur"
		"FgColor_override" "255 0 0 255"
		"bgcolor_override"	"0 0 0 0"
	}
	"CountdownLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"CountdownLabel"
		"xpos"			"0"
		"ypos"			"50"
		"zpos"			"2"
		"wide"			"200"
		"tall"			"15"
		"enabled"		"1"
		"textAlignment"		"center"
		"font" "Countdown"
		"FgColor_override" "255 0 0 128"
		"bgcolor_override"	"0 0 0 0"
	}
	"CountdownGlowLabel"
	{
		"ControlName"		"Label"
		"fieldName"		"CountdownGlowLabel"
		"xpos"			"0"
		"ypos"			"50"
		"zpos"			"1"
		"wide"			"200"
		"tall"			"15"
		"enabled"		"1"
		"textAlignment"		"center"
		"font" "CountdownBlur"
		"FgColor_override" "255 0 0 255"
		"bgcolor_override"	"0 0 0 0"
	}
}