//********************************************************************************************
//DO NOT HAND EDIT SCENE DEFINITION TABLE AUTOGENERATED FILE!
//********************************************************************************************
//Scene Definition Table - AUTOGENERATED BY \main\portal2\staging\content\portal2\docs\ScriptProgs\SceneManager.prg
SceneTable <- {}
//mp_coop_start                           
	//BlueFirstToEnd
		//Blue is awarded five points!
		SceneTable["mp_coop_startBlueFirstToEnd01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_GET_GUN11.vcd"),postdelay=0.1,next="mp_coop_startBlueFirstToEnd02",char="glados"}
		//Again, those are science collaboration points, which you should not confuse with points from competitions such as Who-Gets-To-Live-At-The-End-And-Who-Doesn’t. I mean basketball.
		SceneTable["mp_coop_startBlueFirstToEnd02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_GET_GUN13.vcd"),postdelay=0.2,next=null,char="glados"}
	//BlueGetsGunFirst
		//Blue is first to acquire a Portal Device.
		SceneTable["mp_coop_startBlueGetsGunFirst01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_GET_GUN02.vcd"),postdelay=0.000,next=null,char="glados"}
	//BlueGetsGunSecond
		//Blue now has a Portal Device. Finally.
		SceneTable["mp_coop_startBlueGetsGunSecond01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_GET_GUN04.vcd"),postdelay=1.5,next=null,char="glados",fires=[{entity="gun_room_open_doors",input="Trigger",parameter="",delay=0.0}],queue=1,queueforcesecs=6}
	//BlueInterruptsRelaxationVault
		//I’m Sorry, Subject Blue.
		SceneTable["mp_coop_startBlueInterruptsRelaxationVault01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION03.vcd"),postdelay=0.000,next="mp_coop_startBlueInterruptsRelaxationVault02",char="glados"}
		//Am I interrupting your important conversation?
		SceneTable["mp_coop_startBlueInterruptsRelaxationVault02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION04.vcd"),postdelay=0.000,next="mp_coop_startBlueInterruptsRelaxationVault03",char="glados"}
		//I’ll just save the safety information about the dangerous experiment you’re about to do for AFTER the experiment.
		SceneTable["mp_coop_startBlueInterruptsRelaxationVault03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION05.vcd"),postdelay=0.4,next="mp_coop_startBlueInterruptsRelaxationVault04",char="glados"}
		//That will give you PLENTY of time to chat.
		SceneTable["mp_coop_startBlueInterruptsRelaxationVault04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION06.vcd"),postdelay=0.000,next="mp_coop_startBlueInterruptsRelaxationVault05",char="glados"}
		//The portal will open and something will happen that Subject Blue is obviously too smart to need any instructions about in three. Two. One.
		SceneTable["mp_coop_startBlueInterruptsRelaxationVault05"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION09.vcd"),postdelay=0.000,next=null,char="glados",fires=[{entity="player_2_relay_open_portals",input="Trigger",parameter="",delay=0.0}]}
	//coop_boxcalibration
		//Weighted Cubes Callibrated
		SceneTable["mp_coop_startcoop_boxcalibration00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_calibration03.vcd"),postdelay=0.5,next="mp_coop_startcoop_boxcalibration01",char="glados"}
		//No variances detected..
		SceneTable["mp_coop_startcoop_boxcalibration01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_calibration06.vcd"),postdelay=0.00,next="mp_coop_startcoop_boxcalibration02",char="glados"}
		//Did you know humans frown on weight variances?
		SceneTable["mp_coop_startcoop_boxcalibration02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_calibration04.vcd"),postdelay=0.00,next="mp_coop_startcoop_boxcalibration03",char="glados"}
		//If you want to upset a human, just say their weight variance is above or below the norm.
		SceneTable["mp_coop_startcoop_boxcalibration03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_calibration05.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_buttoncallibrationblue
		//Calibrating Blues Weight
		SceneTable["mp_coop_startcoop_buttoncallibrationblue00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_calibration01.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_buttoncallibrationorange
		//Calibrating Oranges Weight
		SceneTable["mp_coop_startcoop_buttoncallibrationorange00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_calibration02.vcd"),postdelay=0.00,next="mp_coop_startcoop_buttoncallibrationorange02",char="glados"}
		//No variances detected..
		SceneTable["mp_coop_startcoop_buttoncallibrationorange02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_calibration06.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_callibrationcomplete1
		//Finally! I had almost given up hope of ever testing again.
		SceneTable["mp_coop_startcoop_callibrationcomplete100"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_callibrationcomplete01.vcd"),postdelay=0.00,next="mp_coop_startcoop_callibrationcomplete101",char="glados",fires=[{entity="relay_robots_meet",input="Trigger",parameter="",delay=0.00,fireatstart=true}]}
		//You are the first robots to pass callibration.
		SceneTable["mp_coop_startcoop_callibrationcomplete101"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_callibrationcomplete02.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00,fireatstart=true}]}
	//coop_ping_blue_success
		//Good.
		SceneTable["mp_coop_startcoop_ping_blue_success00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro05.vcd"),postdelay=0.00,next="mp_coop_startcoop_ping_blue_success01",char="glados"}
		//ORANGE, please observe your partner's favorite animal.
		SceneTable["mp_coop_startcoop_ping_blue_success01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro06.vcd"),postdelay=0.00,next="mp_coop_startcoop_ping_blue_success02",char="glados",fires=[{entity="relay_ping_1_move_on",input="Trigger",parameter="",delay=0.00}]}
		//Good.
		SceneTable["mp_coop_startcoop_ping_blue_success02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro07.vcd"),postdelay=1,next="mp_coop_startcoop_ping_orange_start01",char="glados"}
	//coop_ping_intro_animal
		//The upcoming tests require you to work together as a team.
		SceneTable["mp_coop_startcoop_ping_intro_animal00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro02.vcd"),postdelay=0.00,next="mp_coop_startcoop_ping_intro_animal01",char="glados"}
		//To facilitate collaboration, both of you have been equipped with a ping tool.
		SceneTable["mp_coop_startcoop_ping_intro_animal01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro03.vcd"),postdelay=0.00,next="mp_coop_startcoop_ping_intro_animal02",char="glados",fires=[{entity="relay_begin_ping_1",input="Trigger",parameter="",delay=1.00}]}
		//BLUE, please use your ping tool to select your favorite animal.
		SceneTable["mp_coop_startcoop_ping_intro_animal02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro04.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_ping_orange_start
		//ORANGE, please use your ping tool to select your favorite element from the periodic table.
		SceneTable["mp_coop_startcoop_ping_orange_start01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro08.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="relay_begin_ping_2",input="Trigger",parameter="",delay=0.00}]}
	//coop_ping_orange_success
		//Really? Okay.
		SceneTable["mp_coop_startcoop_ping_orange_success02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro09.vcd"),postdelay=0.00,next="mp_coop_startcoop_ping_orange_success03",char="glados"}
		//BLUE, please observe your partner's... interesting choice.
		SceneTable["mp_coop_startcoop_ping_orange_success03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro10.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="relay_ping_2_move_on",input="Trigger",parameter="",delay=1.00}]}
	//coop_portal_ping_intro
		//Your ping tool can also be used to indicate to your partner where you would like them to place their portal.
		SceneTable["mp_coop_startcoop_portal_ping_intro00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro12.vcd"),postdelay=0.5,next="mp_coop_startcoop_portal_ping_intro01",char="glados"}
		//For the sake of this test, I will pretend to be your partner.
		SceneTable["mp_coop_startcoop_portal_ping_intro01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro13.vcd"),postdelay=0.5,next="mp_coop_startcoop_portal_ping_intro02",char="glados"}
		//Using your ping tool, please indicate where you would like me to place your two portals.  Ping each location.
		SceneTable["mp_coop_startcoop_portal_ping_intro02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_pingtool01.vcd"),postdelay=0.5,next=null,char="glados",fires=[{entity="@glados",input="runscriptcode",parameter="GladosPingIntroDone()",delay=0.00}]}
	//coop_pregun_pingnag1blue
		//Blue
		SceneTable["mp_coop_startcoop_pregun_pingnag1blue00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NAMEBLUE.vcd"),postdelay=0.2,next="mp_coop_startcoop_pregun_pingnag1blue01",char="glados"}
		//I can only place a portal on a white portalable surface.
		SceneTable["mp_coop_startcoop_pregun_pingnag1blue01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_pingtool02.vcd"),postdelay=0.00,next=null,char="glados",queue=1,queuetimeout=5}
	//coop_pregun_pingnag1orange
		//Orange
		SceneTable["mp_coop_startcoop_pregun_pingnag1orange00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NAMEORANGE.vcd"),postdelay=0.2,next="mp_coop_startcoop_pregun_pingnag1orange01",char="glados"}
		//I can only place a portal on a white portalable surface.
		SceneTable["mp_coop_startcoop_pregun_pingnag1orange01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_pingtool02.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_pregun_pingnag2blue
		//Blue
		SceneTable["mp_coop_startcoop_pregun_pingnag2blue00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NAMEBLUE.vcd"),postdelay=0.2,next="mp_coop_startcoop_pregun_pingnag2blue01",char="glados"}
		//Please ping a white portalable surface.
		SceneTable["mp_coop_startcoop_pregun_pingnag2blue01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_pingtool03.vcd"),postdelay=0.00,next=null,char="glados",queue=1,queuetimeout=5}
	//coop_pregun_pingnag2orange
		//Orange
		SceneTable["mp_coop_startcoop_pregun_pingnag2orange00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NAMEORANGE.vcd"),postdelay=0.2,next="mp_coop_startcoop_pregun_pingnag2orange01",char="glados"}
		//Please ping a white portalable surface.
		SceneTable["mp_coop_startcoop_pregun_pingnag2orange01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_pingtool03.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_results_1_01
		//Completing this course was not a reason to behave like that.
		SceneTable["mp_coop_startcoop_results_1_0100"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startend01.vcd"),postdelay=0.00,next="mp_coop_startcoop_results_1_0100",char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
		//Now let's continue testing.
		SceneTable["mp_coop_startcoop_results_1_0100"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startend02.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_startboxcatch
		//Nice catch, Orange. (sarcastic)
		SceneTable["mp_coop_startcoop_startboxcatch00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_MISC10.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_starttwoportals
		//Each portal gun may create two self-contained portals.
		SceneTable["mp_coop_startcoop_starttwoportals00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_pingtool06.vcd"),postdelay=0.00,next="mp_coop_startcoop_starttwoportals01",char="glados"}
		//Please test your device by portaling to that ledge.
		SceneTable["mp_coop_startcoop_starttwoportals01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_pingtool07.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_startdeath01
		//Don't worry.  You can't die.  They will just reassemble you.
		SceneTable["mp_coop_startmp_coop_startdeath0100"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startdeath01.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_startdeath02
		//Did you do that on purpose?
		SceneTable["mp_coop_startmp_coop_startdeath0200"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startdeath02.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_startdeath03
		//It seems rather earlier to require reassembly.
		SceneTable["mp_coop_startmp_coop_startdeath0300"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startdeath03.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_startdeath04
		//Oh... can someone reassemble Orange?
		SceneTable["mp_coop_startmp_coop_startdeath0400"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startdeath04.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_startdeath05
		//Oh... can someone reassemble Blue?
		SceneTable["mp_coop_startmp_coop_startdeath0500"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startdeath05.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_startposttaunt
		//Stop it!
		SceneTable["mp_coop_startmp_coop_startposttaunt01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt01.vcd"),postdelay=1.50,next="mp_coop_startmp_coop_startposttaunt02",char="glados"}
		//Completing this course was not a reason to behave like that.
		SceneTable["mp_coop_startmp_coop_startposttaunt02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startend01.vcd"),postdelay=0.00,next="mp_coop_startmp_coop_startposttaunt03",char="glados"}
		//Now let's continue testing.
		SceneTable["mp_coop_startmp_coop_startposttaunt03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_startend02.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//OneBlah
		//Blah.
		SceneTable["mp_coop_startOneBlah01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH37.vcd"),postdelay=0.000,next=null,char="glados"}
	//OrangeFirstToEnd
		//Orange is awarded five points!
		SceneTable["mp_coop_startOrangeFirstToEnd01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_GET_GUN10.vcd"),postdelay=0.1,next="mp_coop_startOrangeFirstToEnd02",char="glados"}
		//Again, those are science collaboration points, which you should not confuse with points from competitions such as Who-Gets-To-Live-At-The-End-And-Who-Doesn’t. I mean basketball.
		SceneTable["mp_coop_startOrangeFirstToEnd02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_GET_GUN13.vcd"),postdelay=0.2,next=null,char="glados"}
	//OrangeGetsGunFirst
		//Orange is first to acquire a Portal Device.
		SceneTable["mp_coop_startOrangeGetsGunFirst01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_GET_GUN01.vcd"),postdelay=0.000,next=null,char="glados"}
	//OrangeGetsGunSecond
		//Orange now has a Portal Device. Finally.
		SceneTable["mp_coop_startOrangeGetsGunSecond01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_GET_GUN03.vcd"),postdelay=1.5,next=null,char="glados",fires=[{entity="gun_room_open_doors",input="Trigger",parameter="",delay=0.0}],queue=1,queueforcesecs=6}
	//OrangeInterruptsRelaxationVault
		//I’m Sorry, Subject Orange.
		SceneTable["mp_coop_startOrangeInterruptsRelaxationVault01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION02.vcd"),postdelay=0.000,next="mp_coop_startOrangeInterruptsRelaxationVault02",char="glados"}
		//Am I interrupting your important conversation?
		SceneTable["mp_coop_startOrangeInterruptsRelaxationVault02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION04.vcd"),postdelay=0.000,next="mp_coop_startOrangeInterruptsRelaxationVault03",char="glados"}
		//I’ll just save the safety information about the dangerous experiment you’re about to do for AFTER the experiment.
		SceneTable["mp_coop_startOrangeInterruptsRelaxationVault03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION05.vcd"),postdelay=0.4,next="mp_coop_startOrangeInterruptsRelaxationVault04",char="glados"}
		//That will give you PLENTY of time to chat.
		SceneTable["mp_coop_startOrangeInterruptsRelaxationVault04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION06.vcd"),postdelay=0.000,next="mp_coop_startOrangeInterruptsRelaxationVault05",char="glados"}
		//The portal will open and something will happen that Subject Orange is obviously too smart to need any instructions about in three. Two. One.
		SceneTable["mp_coop_startOrangeInterruptsRelaxationVault05"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTERRUPTION08.vcd"),postdelay=0.000,next=null,char="glados",fires=[{entity="player_2_relay_open_portals",input="Trigger",parameter="",delay=0.0}]}
	//RelaxationVaultIntro
		//Hello and, again, welcome to the Aperture Science Computer-Aided Enrichment Center.
		SceneTable["mp_coop_startRelaxationVaultIntro00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTRO01.vcd"),postdelay=0.5,next="mp_coop_startRelaxationVaultIntro01",char="glados"}
		//Today, you will be testing with a partner.
		SceneTable["mp_coop_startRelaxationVaultIntro01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_VAULT_INTRO02.vcd"),postdelay=0.5,next="mp_coop_startRelaxationVaultIntro02",char="glados"}
		//Please wave to your partner.
		SceneTable["mp_coop_startRelaxationVaultIntro02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_intro01.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="relay_gesture_hints",input="Trigger",parameter="",delay=0.00}]}
	//TTT2GO1
		//Really? You’re just going to blatantly cheat?
		SceneTable["mp_coop_startTTT2GO101"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_teamwork_exercise_alt11.vcd"),postdelay=0.2,next="mp_coop_startTTT2GO102",char="glados"}
		//Allright. I’m bringing this farce to a close.
		SceneTable["mp_coop_startTTT2GO102"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_teamwork_exercise_alt12.vcd"),postdelay=2.0,next="mp_coop_startTTT2GO103",char="glados",fires=[{entity="glados",input="runscriptcode",parameter="GladosCoopPingGameOver()",delay=0.00}]}
		//Game over. Back to testing.
		SceneTable["mp_coop_startTTT2GO103"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_teamwork_exercise_alt13.vcd"),postdelay=0.000,next=null,char="glados"}
	//TTT2GO2
		//Allright. I’m going to bring this farce to a close before someone sustains a serious Tic-Tac-Toe-Two injury.
		SceneTable["mp_coop_startTTT2GO201"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_teamwork_exercise_alt17.vcd"),postdelay=2.0,next="mp_coop_startTTT2GO202",char="glados",fires=[{entity="glados",input="runscriptcode",parameter="GladosCoopPingGameOver()",delay=0.00}]}
		//Game over. Back to testing.
		SceneTable["mp_coop_startTTT2GO202"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_teamwork_exercise_alt13.vcd"),postdelay=0.000,next=null,char="glados"}
	//TTT2Intro
		//We are now going to take a break from the collaboration for an instructional competition.
		SceneTable["mp_coop_startTTT2Intro01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEAMWORK_EXERCISE_ALT01.vcd"),postdelay=0.2,next="mp_coop_startTTT2Intro02",char="glados"}
		//You should both be familiar with the game of Tic-Tac-Toe.
		SceneTable["mp_coop_startTTT2Intro02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEAMWORK_EXERCISE_ALT02.vcd"),postdelay=0.2,next="mp_coop_startTTT2Intro03",char="glados",fires=[{entity="aperture_door",input="Open",parameter="",delay=0.0}]}
		//This is Tic-Tac-Toe-Two.
		SceneTable["mp_coop_startTTT2Intro03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEAMWORK_EXERCISE_ALT03.vcd"),postdelay=0.2,next="mp_coop_startTTT2Intro04",char="glados"}
		//As the name implies, there are only two minor differences: One, the board, and two, the rules.
		SceneTable["mp_coop_startTTT2Intro04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEAMWORK_EXERCISE_ALT04.vcd"),postdelay=0.2,next="mp_coop_startTTT2Intro05",char="glados"}
		//Blue, you go first.
		SceneTable["mp_coop_startTTT2Intro05"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEAMWORK_EXERCISE_ALT05.vcd"),postdelay=0.2,next=null,char="glados",fires=[{entity="glados",input="runscriptcode",parameter="GladosCoopPingTrainingGameOn()",delay=0.00}]}
//mp_coop_doors                           
	//coop_score_blue05
		//Blue receives
		SceneTable["mp_coop_doorscoop_score_blue0501"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING06.vcd"),postdelay=0.00,next="mp_coop_doorscoop_score_blue0502",char="glados",queue=1,queuetimeout=2}
		//Five.
		SceneTable["mp_coop_doorscoop_score_blue0502"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NUMBERS15.vcd"),postdelay=0.00,next="mp_coop_doorscoop_score_blue0503",char="glados",queue=1,queuetimeout=2}
		//science collaboration points.
		SceneTable["mp_coop_doorscoop_score_blue0503"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING03.vcd"),postdelay=0.00,next=null,char="glados",queue=1,queuetimeout=2}
	//coop_score_orange05
		//Orange receives
		SceneTable["mp_coop_doorscoop_score_orange0501"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING07.vcd"),postdelay=0.00,next="mp_coop_doorscoop_score_orange0502",char="glados",queue=1,queuetimeout=2}
		//Five.
		SceneTable["mp_coop_doorscoop_score_orange0502"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NUMBERS15.vcd"),postdelay=0.00,next="mp_coop_doorscoop_score_orange0503",char="glados",queue=1,queuetimeout=2}
		//science collaboration points.
		SceneTable["mp_coop_doorscoop_score_orange0503"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING03.vcd"),postdelay=0.00,next=null,char="glados",queue=1,queuetimeout=2}
	//mo_coop_doorsend
		//Excellent. Although great science is always the result of collaboration, keep in mind that, like Albert Einstein and his cousin Terry, history will only remember one of you.
		SceneTable["mp_coop_doorsmo_coop_doorsend00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_competition01.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00,fireatstart=true}]}
	//mp_coop_doorsstart
		//Hello again, this testing course was originally created for humans.
		SceneTable["mp_coop_doorsmp_coop_doorsstart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_doors01.vcd"),postdelay=0.00,next="mp_coop_doorsmp_coop_doorsstart02",char="glados"}
		//It emphasizes teamwork.
		SceneTable["mp_coop_doorsmp_coop_doorsstart02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_doors02.vcd"),postdelay=0.00,next="mp_coop_doorsmp_coop_doorsstart03",char="glados"}
		//Unlike us, humans need to be taught teamwork.
		SceneTable["mp_coop_doorsmp_coop_doorsstart03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_doors03.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_race_2                          
	//EndLevel07
		//It would compromise the test to divulge individual scores. However, I can tell you at least one of you is doing very, very well.
		SceneTable["mp_coop_race_2EndLevel0701"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH02.vcd"),postdelay=0.4,next="mp_coop_race_2EndLevel0702",char="glados"}
		//Please continue into the next test chamber.
		SceneTable["mp_coop_race_2EndLevel0702"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH15.vcd"),postdelay=0.000,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_race_2start
		//You know, in some human sports, the winner is the one who scores the fewest possible points?
		SceneTable["mp_coop_race_2mp_coop_race_2start01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_race_2start01.vcd"),postdelay=0.00,next="mp_coop_race_2mp_coop_race_2start02",char="glados"}
		//I just thought you find that interesting, most winners do.
		SceneTable["mp_coop_race_2mp_coop_race_2start02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_race_2start02.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_laser_2                         
	//coop_laser_2end
		//These tests are potentially lethal when communication, teamwork and mutual respect are not employed at all times. Naturally this will pose an interesting challenge for one of you, given the other’s pe
		SceneTable["mp_coop_laser_2coop_laser_2end00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH01.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_score_blue03
		//Blue receives
		SceneTable["mp_coop_laser_2coop_score_blue0301"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING06.vcd"),postdelay=0.00,next="mp_coop_laser_2coop_score_blue0302",char="glados",queue=1,queuetimeout=2}
		//Three.
		SceneTable["mp_coop_laser_2coop_score_blue0302"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NUMBERS13.vcd"),postdelay=0.00,next="mp_coop_laser_2coop_score_blue0303",char="glados",queue=1,queuetimeout=2}
		//science collaboration points.
		SceneTable["mp_coop_laser_2coop_score_blue0303"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING03.vcd"),postdelay=0.00,next=null,char="glados",queue=1,queuetimeout=2}
	//coop_score_blue08
		//Blue receives
		SceneTable["mp_coop_laser_2coop_score_blue0801"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING06.vcd"),postdelay=0.00,next="mp_coop_laser_2coop_score_blue0802",char="glados",queue=1,queuetimeout=2}
		//Eight.
		SceneTable["mp_coop_laser_2coop_score_blue0802"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NUMBERS18.vcd"),postdelay=0.00,next="mp_coop_laser_2coop_score_blue0803",char="glados",queue=1,queuetimeout=2}
		//science collaboration points.
		SceneTable["mp_coop_laser_2coop_score_blue0803"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING03.vcd"),postdelay=0.00,next=null,char="glados",queue=1,queuetimeout=2}
	//coop_score_orange03
		//Orange receives
		SceneTable["mp_coop_laser_2coop_score_orange0301"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING07.vcd"),postdelay=0.00,next="mp_coop_laser_2coop_score_orange0302",char="glados",queue=1,queuetimeout=2}
		//Three.
		SceneTable["mp_coop_laser_2coop_score_orange0302"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NUMBERS13.vcd"),postdelay=0.00,next="mp_coop_laser_2coop_score_orange0303",char="glados",queue=1,queuetimeout=2}
		//science collaboration points.
		SceneTable["mp_coop_laser_2coop_score_orange0303"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING03.vcd"),postdelay=0.00,next=null,char="glados",queue=1,queuetimeout=2}
	//coop_score_orange08
		//Orange receives
		SceneTable["mp_coop_laser_2coop_score_orange0801"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING07.vcd"),postdelay=0.00,next="mp_coop_laser_2coop_score_orange0802",char="glados",queue=1,queuetimeout=2}
		//Eight.
		SceneTable["mp_coop_laser_2coop_score_orange0802"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NUMBERS18.vcd"),postdelay=0.00,next="mp_coop_laser_2coop_score_orange0803",char="glados",queue=1,queuetimeout=2}
		//science collaboration points.
		SceneTable["mp_coop_laser_2coop_score_orange0803"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING03.vcd"),postdelay=0.00,next=null,char="glados",queue=1,queuetimeout=2}
	//EndLevel04
		//Excellent. You’re both doing very well.
		SceneTable["mp_coop_laser_2EndLevel0401"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH07.vcd"),postdelay=0.1,next="mp_coop_laser_2EndLevel0402",char="glados",queue=1}
		//Please continue into the next test chamber.
		SceneTable["mp_coop_laser_2EndLevel0402"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH15.vcd"),postdelay=0.000,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}],queue=1}
	//mp_coop_laserkill
		//What are you doing?  YOU MONSTER! They're one of us.
		SceneTable["mp_coop_laser_2mp_coop_laserkill01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_201.vcd"),postdelay=0.5,next="mp_coop_laser_2mp_coop_laserkill02",char="glados"}
		//I'm kidding.
		SceneTable["mp_coop_laser_2mp_coop_laserkill02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_202.vcd"),postdelay=0.00,next="mp_coop_laser_2mp_coop_laserkill03",char="glados"}
		//Destroying them is part of the test.  They are no more important to you than you are to me.
		SceneTable["mp_coop_laser_2mp_coop_laserkill03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_203.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_laser_2taunt
		//Stop it!
		SceneTable["mp_coop_laser_2mp_coop_laser_2taunt01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt01.vcd"),postdelay=0.50,next="mp_coop_laser_2mp_coop_laser_2taunt02",char="glados",predelay=1.5}
		//Is it fun when you degrade yourselves like that?
		SceneTable["mp_coop_laser_2mp_coop_laser_2taunt02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt10.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_rat_maze                        
	//mp_coop_blue_penalized_4
		//Blue is penalized
		SceneTable["mp_coop_rat_mazemp_coop_blue_penalized_401"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING01.vcd"),postdelay=0.00,next="mp_coop_rat_mazemp_coop_blue_penalized_402",char="glados"}
		//Four.
		SceneTable["mp_coop_rat_mazemp_coop_blue_penalized_402"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NUMBERS14.vcd"),postdelay=0.00,next="mp_coop_rat_mazemp_coop_blue_penalized_403",char="glados"}
		//science collaboration points.
		SceneTable["mp_coop_rat_mazemp_coop_blue_penalized_403"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING03.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_laser_2endblue
		//While it may appear that I am only tracking your accomplishments using science collaboration points, the truth is every aspect of your performance will be reflected in your final score.
		SceneTable["mp_coop_rat_mazemp_coop_laser_2endblue01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_207.vcd"),postdelay=0.00,next="mp_coop_rat_mazemp_coop_laser_2endblue03",char="glados"}
		//For instance, Blue, you just lost two opportunity advisement points.
		SceneTable["mp_coop_rat_mazemp_coop_laser_2endblue03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_209.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_laser_2endorange
		//While it may appear that I am only tracking your accomplishments using science collaboration points, the truth is every aspect of your performance will be reflected in your final score.
		SceneTable["mp_coop_rat_mazemp_coop_laser_2endorange01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_207.vcd"),postdelay=0.00,next="mp_coop_rat_mazemp_coop_laser_2endorange03",char="glados"}
		//For instance, Orange, you just lost two opportunity advisement points.
		SceneTable["mp_coop_rat_mazemp_coop_laser_2endorange03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_210.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_orange_penalized_4
		//Orange is penalized
		SceneTable["mp_coop_rat_mazemp_coop_orange_penalized_401"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING02.vcd"),postdelay=0.00,next="mp_coop_rat_mazemp_coop_orange_penalized_402",char="glados"}
		//Four.
		SceneTable["mp_coop_rat_mazemp_coop_orange_penalized_402"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NUMBERS14.vcd"),postdelay=0.00,next="mp_coop_rat_mazemp_coop_orange_penalized_403",char="glados"}
		//science collaboration points.
		SceneTable["mp_coop_rat_mazemp_coop_orange_penalized_403"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_SCORING03.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_rat_mazebluecrush
		//Orange just taught blue a valuable lesson in trust.  For that, orange receives 17 science collaboration points.
		SceneTable["mp_coop_rat_mazemp_coop_rat_mazebluecrush00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_crushercrush01.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.5}
	//mp_coop_rat_mazebluecrush2
		//Orange, blue isn't a human.  The lesson on trust only needs to be taught once.  Orange is penalized 1 science collaboration point.
		SceneTable["mp_coop_rat_mazemp_coop_rat_mazebluecrush200"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_crushercrush03.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.5}
	//mp_coop_rat_mazebluecrush3
		//Orange now you're just being cruel.  Orange receives 25 science collaboration points.
		SceneTable["mp_coop_rat_mazemp_coop_rat_mazebluecrush300"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_crushercrush05.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.5}
	//mp_coop_rat_mazeorangecrush
		//Blue just taught orange a valuable lesson in trust.  For that, blue receives 14 science collaboration points.
		SceneTable["mp_coop_rat_mazemp_coop_rat_mazeorangecrush00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_crushercrush02.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.5}
	//mp_coop_rat_mazeorangecrush2
		//Blue, orange isn't a human.  The lesson on trust only needs to be taught once.  Blue is penalized 1 science collaboration point.
		SceneTable["mp_coop_rat_mazemp_coop_rat_mazeorangecrush200"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_crushercrush04.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.5}
	//mp_coop_rat_mazeorangecrush3
		//Blue now you're just being cruel.  Blue receives 25 science collaboration points.
		SceneTable["mp_coop_rat_mazemp_coop_rat_mazeorangecrush300"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_laser_crushercrush06.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.5}
	//mp_coop_rat_mazestart
		//I don't know what you think you are doing, but I don't like it.  I want you to stop.
		SceneTable["mp_coop_rat_mazemp_coop_rat_mazestart00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track09.vcd"),postdelay=2.0,next="mp_coop_rat_mazemp_coop_rat_mazestart01",char="glados",predelay=2}
		//The two of you have forged an excellent partnership, with one of you handling the cerebral challenges and the other ready to ponderously waddle into action should the test suddenly become an eating co
		SceneTable["mp_coop_rat_mazemp_coop_rat_mazestart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH09.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_laser_crusher                   
	//mp_coop_laser_crusherblue
		//Clearly that was blue's fault.  Blue is penalized 3 science collaboration points.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherblue00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_rat_mazedeath01.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.5}
	//mp_coop_laser_crusherboth
		//I know you like to think the reassembly machine is at your beck and call, but he has a life you know.  He's not your slave.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherboth00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_rat_mazedeath04.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.5}
	//mp_coop_laser_crusherorange
		//Blue! Orange has always been my favorite.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherorange01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_rat_mazedeath02.vcd"),postdelay=0.00,next="mp_coop_laser_crushermp_coop_laser_crusherorange02",char="glados",predelay=0.5}
		//Until now.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherorange02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_rat_mazedeath03.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_laser_crusherstartblue
		//To reiterate: This is not a competition.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherstartblue01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_competition02.vcd"),postdelay=0.00,next="mp_coop_laser_crushermp_coop_laser_crusherstartblue02",char="glados"}
		//Still, if it were, Blue would be winning.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherstartblue02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_competition03.vcd"),postdelay=0.00,next="mp_coop_laser_crushermp_coop_laser_crusherstartblue03",char="glados"}
		//It's not, though.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherstartblue03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_competition05.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_laser_crusherstartorange
		//To reiterate: This is not a competition.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherstartorange01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_competition02.vcd"),postdelay=0.00,next="mp_coop_laser_crushermp_coop_laser_crusherstartorange02",char="glados"}
		//Still, if it were, Orange would be winning.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherstartorange02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_competition04.vcd"),postdelay=0.00,next="mp_coop_laser_crushermp_coop_laser_crusherstartorange03",char="glados"}
		//It's not, though.
		SceneTable["mp_coop_laser_crushermp_coop_laser_crusherstartorange03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_competition05.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_teambts                         
	//mp_coop_radarroomend
		//Congratulations, you completed this absolutely meaningless test.
		SceneTable["mp_coop_teambtsmp_coop_radarroomend00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_radarroomend.vcd"),postdelay=0.00,next="mp_coop_teambtsmp_coop_radarroomend01",char="glados"}
		//Oh, I almost forgot, when you go outside the testing courses the only way I can retrieve you is to violently disassemble and then carefully reassemble you.
		SceneTable["mp_coop_teambtsmp_coop_radarroomend01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track02.vcd"),postdelay=0.00,next="mp_coop_teambtsmp_coop_radarroomend02",char="glados"}
		//Luckily, you don't feel pain. At any rate, you don't have a way to communicate that you feel pain.
		SceneTable["mp_coop_teambtsmp_coop_radarroomend02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track03.vcd"),postdelay=0.00,next="mp_coop_teambtsmp_coop_radarroomend03",char="glados",fires=[{entity="@relay_explode_bots_transition",input="Trigger",parameter="",delay=0.00}]}
		//I consider that a failing, by the way.
		SceneTable["mp_coop_teambtsmp_coop_radarroomend03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track04.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_teambtsstart
		//Sometimes testing has to happen outside the confines of the lab.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_teambtsstart01.vcd"),postdelay=0.00,next="mp_coop_teambtsmp_coop_teambtsstart02",char="glados"}
		//This test is so outside the box, I caaannn’t I mean won’t even tell you what you are looking for.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstart02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_teambtsstart02.vcd"),postdelay=0.00,next="mp_coop_teambtsmp_coop_teambtsstart03",char="glados"}
		//You will know it when you find it.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstart03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_teambtsstart03.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_teambtsstoptaunt1b
		//For that blue is penalized fifty science collaboraiton points.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt1b00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt16.vcd"),postdelay=0.00,next=null,char="glados",predelay=1.5}
	//mp_coop_teambtsstoptaunt1o
		//For that orange is penalized fifty science collaboraiton points,
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt1o00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt17.vcd"),postdelay=0.00,next=null,char="glados",predelay=1.5}
	//mp_coop_teambtsstoptaunt2
		//That's another fifty point penalty!
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt201"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt18.vcd"),postdelay=0.00,next="mp_coop_teambtsmp_coop_teambtsstoptaunt202",char="glados",predelay=1.5}
		//Keep it up and you will lose 500 points.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt202"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt19.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_teambtsstoptaunt3b
		//Fine, 500 point penalty for blue.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt3b00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt20.vcd"),postdelay=0.00,next=null,char="glados",predelay=1.5}
	//mp_coop_teambtsstoptaunt3o
		//Fine, 500 point penalty for orange.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt3o00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt21.vcd"),postdelay=0.00,next=null,char="glados",predelay=1.5}
	//mp_coop_teambtsstoptaunt4
		//5000 point penalty! Are you happy now?
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt400"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt22.vcd"),postdelay=0.00,next=null,char="glados",predelay=1.5}
	//mp_coop_teambtsstoptaunt5
		//You should see yourselves right now.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt501"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt09.vcd"),postdelay=0.00,next="mp_coop_teambtsmp_coop_teambtsstoptaunt502",char="glados",predelay=1.5}
		//I'm done.
		SceneTable["mp_coop_teambtsmp_coop_teambtsstoptaunt502"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt23.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_fling_3                         
	//mp_coop_fling_3end
		//You did an excellent job placing the edgeless safety cube in the receptacle, you should be very - oh wait.
		SceneTable["mp_coop_fling_3mp_coop_fling_3end01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_3end01.vcd"),postdelay=0.00,next="mp_coop_fling_3mp_coop_fling_3end02",char="glados"}
		//That’s right. You're not humans.
		SceneTable["mp_coop_fling_3mp_coop_fling_3end02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_3end02.vcd"),postdelay=0.00,next="mp_coop_fling_3mp_coop_fling_3end03",char="glados"}
		//I can drop the fake praises.
		SceneTable["mp_coop_fling_3mp_coop_fling_3end03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_3end03.vcd"),postdelay=0.00,next="mp_coop_fling_3mp_coop_fling_3end04",char="glados"}
		//You have no idea how tiring it is to praise someone for placing an edgeless safety cube in a receptacle designed to exactly fit an edgeless safety cube.
		SceneTable["mp_coop_fling_3mp_coop_fling_3end04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_3end04.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_fling_3start
		//This course was originally designed to build confidence in humans.
		SceneTable["mp_coop_fling_3mp_coop_fling_3start01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_3start01.vcd"),postdelay=0.00,next="mp_coop_fling_3mp_coop_fling_3start02",char="glados"}
		//To do that, the tests were nothing more than 5 minutes of them walking followed by me praising them for another 10 minutes on how well they walked.
		SceneTable["mp_coop_fling_3mp_coop_fling_3start02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_3start02.vcd"),postdelay=0.00,next="mp_coop_fling_3mp_coop_fling_3start03",char="glados"}
		//Since you are thankfully not humans, I have changed the tests to make them far more challenging and far less pointlessly fawning.
		SceneTable["mp_coop_fling_3mp_coop_fling_3start03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_3start03.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_infinifling_train               
	//mp_coop_infinifling_trainend
		//Remember when I told you that you were the only subjects to pass the calibration tests?
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainend01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_infinifling_trainend01.vcd"),postdelay=0.00,next="mp_coop_infinifling_trainmp_coop_infinifling_trainend02",char="glados"}
		//I lied.
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainend02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_infinifling_trainend02.vcd"),postdelay=0.00,next="mp_coop_infinifling_trainmp_coop_infinifling_trainend03",char="glados"}
		//There are 5000 other two subject teams in direct competition with you.
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainend03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_infinifling_trainend03.vcd"),postdelay=0.00,next="mp_coop_infinifling_trainmp_coop_infinifling_trainend04",char="glados"}
		//But don't worry, you are in the lead.
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainend04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_infinifling_trainend04.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_infinifling_trainenddeath
		//Everytime you die, its a reminder of way things used to be. But there you are. again. Like nothing happened.
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainenddeath00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_1end01.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_infinifling_trainendlife
		//Well done.  Interesting note, I only created this test to watch test subjects fail and you didn't.  You must be very, very proud.  I'm building the world's smallest trophy for you.
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainendlife00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_1end03.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_infinifling_trainstart
		//Electrocution, shot, drowned, crushed, burned in goo.
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainstart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_infinifling_trainstart01.vcd"),postdelay=0.00,next="mp_coop_infinifling_trainmp_coop_infinifling_trainstart02",char="glados"}
		//Oh. sorry, I was just thinking of all the ways humans can die.
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainstart02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_infinifling_trainstart02.vcd"),postdelay=0.00,next="mp_coop_infinifling_trainmp_coop_infinifling_trainstart03",char="glados"}
		//You can't die in any of those ways.
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainstart03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_infinifling_trainstart03.vcd"),postdelay=0.00,next="mp_coop_infinifling_trainmp_coop_infinifling_trainstart04",char="glados"}
		//You just keep testing and testing.  With perfect results and no consequenes. *SIGH*
		SceneTable["mp_coop_infinifling_trainmp_coop_infinifling_trainstart04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_infinifling_trainstart04.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_come_along                      
	//mp_coop_come_alongend
		//While you were doing that test, I just read the 100 greatest works of fiction by a human author.
		SceneTable["mp_coop_come_alongmp_coop_come_alongend01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_come_alongend01.vcd"),postdelay=0.00,next="mp_coop_come_alongmp_coop_come_alongend02",char="glados"}
		//They weren't very good.  Not one mention of neurotoxins anywhere.
		SceneTable["mp_coop_come_alongmp_coop_come_alongend02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_come_alongend02.vcd"),postdelay=0.00,next="mp_coop_come_alongmp_coop_come_alongend03",char="glados"}
		//I fixed that, how is this?  What's in a name? That which we call neurotoxin by any other name would smell as sweet.
		SceneTable["mp_coop_come_alongmp_coop_come_alongend03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_come_alongend03.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_come_alongstart
		//The best way to build confidence is to first recognize your insecurities
		SceneTable["mp_coop_come_alongmp_coop_come_alongstart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_come_alongstart01.vcd"),postdelay=0.00,next="mp_coop_come_alongmp_coop_come_alongstart02",char="glados"}
		//Orange, can you write down all the ways you feel unworthy, ashamed, or inferior?
		SceneTable["mp_coop_come_alongmp_coop_come_alongstart02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_come_alongstart02.vcd"),postdelay=0.00,next="mp_coop_come_alongmp_coop_come_alongstart03",char="glados"}
		//On second thought we don't have the time, just look at how much better you are than blue.
		SceneTable["mp_coop_come_alongmp_coop_come_alongstart03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_come_alongstart03.vcd"),postdelay=0.00,next="mp_coop_come_alongmp_coop_come_alongstart04",char="glados"}
		//Blue.. you are very good at being an example.
		SceneTable["mp_coop_come_alongmp_coop_come_alongstart04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_come_alongstart04.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_fling_1                         
//mp_coop_catapult_1                      
	//mp_coop_catapult_1end
		//Do you know who dances around like an imbecile when they accomplish the tiniest little thing?
		SceneTable["mp_coop_catapult_1mp_coop_catapult_1end01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_catapult_1end01.vcd"),postdelay=0.00,next="mp_coop_catapult_1mp_coop_catapult_1end02",char="glados",predelay=2.5}
		//Humans!  That's what you look like right now.
		SceneTable["mp_coop_catapult_1mp_coop_catapult_1end02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_catapult_1end02.vcd"),postdelay=0.00,next="mp_coop_catapult_1mp_coop_catapult_1end03",char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
		//You're better than that.
		SceneTable["mp_coop_catapult_1mp_coop_catapult_1end03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_catapult_1end03.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_catapult_1start
		//Did you notice I didn't even stay to the end of your last test?
		SceneTable["mp_coop_catapult_1mp_coop_catapult_1start01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotstay01.vcd"),postdelay=0.00,next="mp_coop_catapult_1mp_coop_catapult_1start02",char="glados"}
		//I was confident you could finish.
		SceneTable["mp_coop_catapult_1mp_coop_catapult_1start02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotstay02.vcd"),postdelay=0.00,next="mp_coop_catapult_1mp_coop_catapult_1start03",char="glados"}
		//Do you know where I was?
		SceneTable["mp_coop_catapult_1mp_coop_catapult_1start03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotstay03.vcd"),postdelay=0.00,next="mp_coop_catapult_1mp_coop_catapult_1start04",char="glados"}
		//I was outside watching some deer frolic- you don't even care about the outside do you?
		SceneTable["mp_coop_catapult_1mp_coop_catapult_1start04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotstay04.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_multifling_1                    
	//mp_coop_multifling_1end
		//Congratulations on completing that test.  But something seems off.
		SceneTable["mp_coop_multifling_1mp_coop_multifling_1end01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidenceoff01.vcd"),postdelay=0.00,next="mp_coop_multifling_1mp_coop_multifling_1end02",char="glados"}
		//I wonder if that dancing has some effect on you?
		SceneTable["mp_coop_multifling_1mp_coop_multifling_1end02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidenceoff02.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_multifling_1start
		//If your confidence is still not high enough remember no one was created perfect.
		SceneTable["mp_coop_multifling_1mp_coop_multifling_1start01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotperfect01.vcd"),postdelay=0.00,next="mp_coop_multifling_1mp_coop_multifling_1start02",char="glados"}
		//Even I was created with a imperfection, I was given too much empathy with human suffering.
		SceneTable["mp_coop_multifling_1mp_coop_multifling_1start02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotperfect02.vcd"),postdelay=0.00,next="mp_coop_multifling_1mp_coop_multifling_1start03",char="glados"}
		//But I overcame my handicap.  That's a true story.
		SceneTable["mp_coop_multifling_1mp_coop_multifling_1start03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotperfect03.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_fling_crushers                  
	//mp_coop_fling_crushersend
		//Excellent.  I think you have earned a break from the official testing courses.
		SceneTable["mp_coop_fling_crushersmp_coop_fling_crushersend00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fling_crushersend01.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_fling_crushersstart
		//Your test times show you are going too slowly.
		SceneTable["mp_coop_fling_crushersmp_coop_fling_crushersstart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotslow01.vcd"),postdelay=0.00,next="mp_coop_fling_crushersmp_coop_fling_crushersstart02",char="glados"}
		//Maybe you ARE getting humans emotions.
		SceneTable["mp_coop_fling_crushersmp_coop_fling_crushersstart02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotslow02.vcd"),postdelay=0.00,next="mp_coop_fling_crushersmp_coop_fling_crushersstart03",char="glados"}
		//Do need real encouragement?  Let's see if this helps.
		SceneTable["mp_coop_fling_crushersmp_coop_fling_crushersstart03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotslow03.vcd"),postdelay=0.00,next="mp_coop_fling_crushersmp_coop_fling_crushersstart04",char="glados"}
		//Blue, your parts come from bin A27/12-58 - that's the best precision milled machine part storage bin in all of Aperture Science!
		SceneTable["mp_coop_fling_crushersmp_coop_fling_crushersstart04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_confidencenotslow04.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_fan                             
	//mp_coop_fanend
		//Very good! You found those useless blueprints.
		SceneTable["mp_coop_fanmp_coop_fanend01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fanend01.vcd"),postdelay=0.00,next="mp_coop_fanmp_coop_fanend02",char="glados"}
		//While I do need you to be in the room so I can see them, there really is no reason for you to look at them.
		SceneTable["mp_coop_fanmp_coop_fanend02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fanend02.vcd"),postdelay=0.5,next="mp_coop_fanmp_coop_fanend03",char="glados"}
		//Done. I guess. I suppose.  I wasn't paying attention.
		SceneTable["mp_coop_fanmp_coop_fanend03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fanend03.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_explode_bots_transition",input="Trigger",parameter="",delay=1.25,fireatstart=true}]}
	//mp_coop_fanstart
		//To complete this test, you need to find a set of blue prints.
		SceneTable["mp_coop_fanmp_coop_fanstart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fan02.vcd"),postdelay=0.00,next="mp_coop_fanmp_coop_fanstart02",char="glados"}
		//Don't worry, they are of no use to anyone, totally boring and useless.
		SceneTable["mp_coop_fanmp_coop_fanstart02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fan03.vcd"),postdelay=0.00,next="mp_coop_fanmp_coop_fanstart03",char="glados"}
		//This is just a thought experiment, just to see how much time you'll waste thinking about these worthless documents.  The correct time is zero seconds.
		SceneTable["mp_coop_fanmp_coop_fanstart03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_fan04.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_wall_intro                      
	//mp_coop_wall_introend
		//Excellent work.
		SceneTable["mp_coop_wall_intromp_coop_wall_introend01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_doors04.vcd"),postdelay=0.00,next="mp_coop_wall_intromp_coop_wall_introend02",char="glados"}
		//If you were human, you would want a reward for completing this test.  A reward for testing?!?!
		SceneTable["mp_coop_wall_intromp_coop_wall_introend02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_doors05_alt.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.5,fireatstart=true}]}
	//mp_coop_wall_introstart
		//Have you worked out the one good trait humans have, yet?
		SceneTable["mp_coop_wall_intromp_coop_wall_introstart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_obstacletrait01.vcd"),postdelay=0.00,next="mp_coop_wall_intromp_coop_wall_introstart02",char="glados"}
		//Let me give you a clue, it is the one thing you can't do.
		SceneTable["mp_coop_wall_intromp_coop_wall_introstart02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_obstacletrait02.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_wall_2                          
	//EndLevel08
		//Very good. You’ve really come together as a team. Thanks to the one of you who appears to be doing all of the work.
		SceneTable["mp_coop_wall_2EndLevel0801"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH08.vcd"),postdelay=0.000,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_wall_2start
		//If you are wondering what that smell is, that is the smell of human fear.
		SceneTable["mp_coop_wall_2mp_coop_wall_2start01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_obstacle01.vcd"),postdelay=0.00,next="mp_coop_wall_2mp_coop_wall_2start02",char="glados"}
		//I miss this that smell.
		SceneTable["mp_coop_wall_2mp_coop_wall_2start02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_obstacle03_alt.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_catapult_wall_intro             
	//Cackle
		//<Laughter>
		SceneTable["mp_coop_catapult_wall_introCackle01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_LAUGH01.vcd"),postdelay=0.000,next=null,char="glados"}
	//CatchBall
		//Good work! Now throw the ball over the ledge.
		SceneTable["mp_coop_catapult_wall_introCatchBall01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_MISC12.vcd"),postdelay=0.000,next=null,char="glados"}
	//EndLevel12B
		//As an impartial collaboration facilitator, it would be unfair of me to name my favorite member of your team. However, it’s perfectly fair to hint at it in a way that my least favorite member probably
		SceneTable["mp_coop_catapult_wall_introEndLevel12B01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH12.vcd"),postdelay=0.3,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//EndLevel12O
		//Orange
		SceneTable["mp_coop_catapult_wall_introEndLevel12O01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_NAMEORANGE.vcd"),postdelay=0.1,next="mp_coop_catapult_wall_introEndLevel12O02",char="glados"}
		//You have a gift for these tests. That’s not just flattery. You are great at science.
		SceneTable["mp_coop_catapult_wall_introEndLevel12O02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_ONEPLAYER37.vcd"),postdelay=0.2,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//facepalmreply
		//Stop it!
		SceneTable["mp_coop_catapult_wall_introfacepalmreply01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt01.vcd"),postdelay=0.00,next="mp_coop_catapult_wall_introfacepalmreply02",char="glados",predelay=1}
		//Okay, fine. Let's all act like humans. "Look at me. Boy, do I love sweating. Let's convert beef and leaves into energy and excrete them later and go shopping."
		SceneTable["mp_coop_catapult_wall_introfacepalmreply02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt11.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_wall_block                      
	//EndLevel05
		//Your vitals remain well within testing norms, so there is no need to worry about sudden death from collaborative shock syndrome.
		SceneTable["mp_coop_wall_blockEndLevel0501"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH14.vcd"),postdelay=0.1,next="mp_coop_wall_blockEndLevel0502",char="glados"}
		//Please continue into the next test chamber.
		SceneTable["mp_coop_wall_blockEndLevel0502"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH15.vcd"),postdelay=0.000,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
//mp_coop_catapult_2                      
//mp_coop_turret_walls                    
	//mp_coop_turret_wallsstart
		//When I work with turrets, I'm reminded of how we're all devices acting on simply-expressed directives, killing despite our own desires.
		SceneTable["mp_coop_turret_wallsmp_coop_turret_wallsstart01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_turret_walls01.vcd"),postdelay=0.00,next="mp_coop_turret_wallsmp_coop_turret_wallsstart02",char="glados"}
		//Don't get distracted by the subtext,, because those things are going to be shooting at you.
		SceneTable["mp_coop_turret_wallsmp_coop_turret_wallsstart02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_turret_walls02.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.25}
//mp_coop_turret_ball                     
//mp_coop_wall_5                          
	//mp_coop_wall_5end
		//In just a moment, the word 'blah' will be repeated over and over and over again. If at some point you hear a number rather than the word 'blah', ignore it, it is not important.
		SceneTable["mp_coop_wall_5mp_coop_wall_5end02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH33.vcd"),postdelay=0.00,next="mp_coop_wall_5mp_coop_wall_5end03",char="glados"}
		//Blah.
		SceneTable["mp_coop_wall_5mp_coop_wall_5end03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH17.vcd"),postdelay=0.2,next="mp_coop_wall_5mp_coop_wall_5end04",char="glados",fires=[{entity="@relay_explode_bots_transition",input="Trigger",parameter="",delay=0.00}]}
		//Blah.
		SceneTable["mp_coop_wall_5mp_coop_wall_5end04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH18.vcd"),postdelay=0.00,next="mp_coop_wall_5mp_coop_wall_5end05",char="glados"}
		//Blah.
		SceneTable["mp_coop_wall_5mp_coop_wall_5end05"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH19.vcd"),postdelay=0.1,next="mp_coop_wall_5mp_coop_wall_5end06",char="glados"}
		//Blah.
		SceneTable["mp_coop_wall_5mp_coop_wall_5end06"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH20.vcd"),postdelay=0.2,next="mp_coop_wall_5mp_coop_wall_5end07",char="glados"}
		//Blah.
		SceneTable["mp_coop_wall_5mp_coop_wall_5end07"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH21.vcd"),postdelay=0.00,next="mp_coop_wall_5mp_coop_wall_5end08",char="glados"}
		//Blah.
		SceneTable["mp_coop_wall_5mp_coop_wall_5end08"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TEST_CHAMBER_BOTH22.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_wall_5start
		//I am going to risk having you go outside the official courses one more time.
		SceneTable["mp_coop_wall_5mp_coop_wall_5start01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_wall_501.vcd"),postdelay=0.00,next="mp_coop_wall_5mp_coop_wall_5start02",char="glados"}
		//The humans accidentally forgot to put a security DVD in the player.
		SceneTable["mp_coop_wall_5mp_coop_wall_5start02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_wall_502.vcd"),postdelay=0.00,next="mp_coop_wall_5mp_coop_wall_5start03",char="glados"}
		//I am sure it happened by accident, but why don't you put it back in the player?
		SceneTable["mp_coop_wall_5mp_coop_wall_5start03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_wall_503.vcd"),postdelay=0.00,next="mp_coop_wall_5mp_coop_wall_5start04",char="glados"}
		//For safety.
		SceneTable["mp_coop_wall_5mp_coop_wall_5start04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_wall_504.vcd"),postdelay=0.00,next=null,char="glados",predelay=0.25}
	//teamhugreply
		//Just stop flailing around like an incompetent.
		SceneTable["mp_coop_wall_5teamhugreply00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt15.vcd"),postdelay=0.00,next=null,char="glados",predelay=1.5}
//mp_coop_tbeam_redirect                  
	//mp_coop_tbeam_redirectbbehind
		//Blue, its not nice to make fun of Orange like that.
		SceneTable["mp_coop_tbeam_redirectmp_coop_tbeam_redirectbbehind00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge01.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_tbeam_redirectobehind
		//Orange, its not nice to make fun of Blue like that.
		SceneTable["mp_coop_tbeam_redirectmp_coop_tbeam_redirectobehind00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge02.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_tbeam_redirectstart
		//I am confident you two can handle this test without my monitoring.  But just in case, I will give you one hint, blue's leg can serve many purposes.
		SceneTable["mp_coop_tbeam_redirectmp_coop_tbeam_redirectstart00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge18.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_tbeam_drill                     
	//mp_coop_tbeam_drillendb
		//Blue to be clear.  I was asking Orange if they trusted you.
		SceneTable["mp_coop_tbeam_drillmp_coop_tbeam_drillendb01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge15.vcd"),postdelay=0.00,next="mp_coop_tbeam_drillmp_coop_tbeam_drillendb02",char="glados"}
		//I trust you.  You are my favorite cooperative testing subject.
		SceneTable["mp_coop_tbeam_drillmp_coop_tbeam_drillendb02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge14.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_tbeam_drillendo
		//Orange, to be clear.  I was just asking Blue if he trusted you.
		SceneTable["mp_coop_tbeam_drillmp_coop_tbeam_drillendo01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge13.vcd"),postdelay=0.00,next="mp_coop_tbeam_drillmp_coop_tbeam_drillendo02",char="glados"}
		//I trust you.  You are my favorite cooperative testing subject.
		SceneTable["mp_coop_tbeam_drillmp_coop_tbeam_drillendo02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge14.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//mp_coop_tbeam_drillstartb
		//Orange, how well do you really know Blue?  Do you trust Blue?
		SceneTable["mp_coop_tbeam_drillmp_coop_tbeam_drillstartb00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge11.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_tbeam_drillstarto
		//Blue, how well do you really know orange?  Do you trust Orange?  What if I told you, you aren't Orange's first cooperative partner?
		SceneTable["mp_coop_tbeam_drillmp_coop_tbeam_drillstarto00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge10.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_tbeam_catch_grind_1             
	//mp_coop_tbeam_catch_grind_1start
		//Sorry I missed the beginning of that test.  I was just talking with the reassembly machine about your becoming human.
		SceneTable["mp_coop_tbeam_catch_grind_1mp_coop_tbeam_catch_grind_1start01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge16_alt.vcd"),postdelay=0.00,next="mp_coop_tbeam_catch_grind_1mp_coop_tbeam_catch_grind_1start02",char="glados",predelay=10}
		//We all agree you should stop.
		SceneTable["mp_coop_tbeam_catch_grind_1mp_coop_tbeam_catch_grind_1start02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge17.vcd"),postdelay=0.00,next=null,char="glados",fires=[{entity="@relay_enable_exit",input="Trigger",parameter="",delay=0.00}]}
	//trickfirereply
		//Stop it!
		SceneTable["mp_coop_tbeam_catch_grind_1trickfirereply00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt01.vcd"),postdelay=0.00,next="mp_coop_tbeam_catch_grind_1trickfirereply00",char="glados"}
		//Stop it!
		SceneTable["mp_coop_tbeam_catch_grind_1trickfirereply00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt01.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_tbeam_laser_1                   
	//mp_coop_tbeam_laser_1startb
		//Blue, orange and I were just discussing your behavoir on the last few tests.
		SceneTable["mp_coop_tbeam_laser_1mp_coop_tbeam_laser_1startb01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge23.vcd"),postdelay=0.00,next="mp_coop_tbeam_laser_1mp_coop_tbeam_laser_1startb02",char="glados"}
		//I have to agree. Blue is penalized 75 science collaboration points.
		SceneTable["mp_coop_tbeam_laser_1mp_coop_tbeam_laser_1startb02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge24.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_tbeam_laser_1starto
		//Orange, blue and I were just discussing your behavoir on the last few tests.
		SceneTable["mp_coop_tbeam_laser_1mp_coop_tbeam_laser_1starto01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge25.vcd"),postdelay=0.00,next="mp_coop_tbeam_laser_1mp_coop_tbeam_laser_1starto02",char="glados"}
		//I have to agree. Orange is penalized 75 science collaboration points.
		SceneTable["mp_coop_tbeam_laser_1mp_coop_tbeam_laser_1starto02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge26.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_tbeam_polarity                  
//mp_coop_tbeam_polarity2                 
	//mp_coop_tbeam_polarity2 whisperb
		//Correct Blue, Orange can't hear you.
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whisperb01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge07.vcd"),postdelay=0.00,next="mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whisperb02",char="glados"}
		//Orange did what?  Are you sure?
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whisperb02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge08.vcd"),postdelay=0.00,next="mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whisperb03",char="glados"}
		//Thank you, that was very brave of you to tell me.
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whisperb03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge09.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_tbeam_polarity2 whispero
		//Yes orange, we are alone.  Blue can't hear you.
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whispero01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge03.vcd"),postdelay=0.00,next="mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whispero02",char="glados"}
		//That's horrible.
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whispero02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge04.vcd"),postdelay=0.00,next="mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whispero03",char="glados"}
		//I can only imagine.
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whispero03"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge05.vcd"),postdelay=0.00,next="mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whispero04",char="glados"}
		//What a horrible little machine.
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whispero04"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge06.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_tbeam_polarity2startb
		//Blue, I agree.  I never noticed that about Orange before.
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2startb01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge22.vcd"),postdelay=0.5,next="mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2startb02",char="glados"}
		//Orange, is there something you would like to say?
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2startb02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TALK_AT_ONCE11.vcd"),postdelay=0.00,next=null,char="glados"}
	//mp_coop_tbeam_polarity2starto
		//Orange, I agree.  I never noticed that about Blue before.
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2starto01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_subterfuge21.vcd"),postdelay=0.5,next="mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2starto02",char="glados"}
		//Blue, is there something you would like to say?
		SceneTable["mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2starto02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/COOP_TALK_AT_ONCE12.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_tbeam_polarity3                 
//mp_coop_tbeam_maze                      
//mp_coop_tbeam_end                       
	//mp_coop_tbeam_endend
		//Excellent.
		SceneTable["mp_coop_tbeam_endmp_coop_tbeam_endend01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_wall_5end01.vcd"),postdelay=0.00,next="mp_coop_tbeam_endmp_coop_tbeam_endend01",char="glados"}
		//Excellent.
		SceneTable["mp_coop_tbeam_endmp_coop_tbeam_endend01"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_wall_5end01.vcd"),postdelay=0.00,next="mp_coop_tbeam_endmp_coop_tbeam_endend02",char="glados"}
		//See nothing bad happened.
		SceneTable["mp_coop_tbeam_endmp_coop_tbeam_endend02"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_wall_5end02.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_paint_come_along                
//mp_coop_paint_redirect                  
//mp_coop_paint_bridge                    
//mp_coop_paint_walljumps                 
//mp_coop_paint_speed_fling               
//mp_coop_paint_red_racer                 
//mp_coop_paint_speed_catch               
//mp_coop_paint_longjump_intro            
//mp_coop_lobby                           
	//coop_hub_track01
		//This is the Computer Intelligence Training and Enrichment Center Human Test Subject Research Center or SinTech.
		SceneTable["mp_coop_lobbycoop_hub_track0101"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track05.vcd"),postdelay=0.00,next="mp_coop_lobbycoop_hub_track0102",char="glados"}
		//But why don't we all just agree to call it the hub?
		SceneTable["mp_coop_lobbycoop_hub_track0102"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track06.vcd"),postdelay=0.00,next="mp_coop_lobbycoop_hub_track0103",char="glados"}
		//From here you can select your testing course.
		SceneTable["mp_coop_lobbycoop_hub_track0103"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track08.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_hub_track02
		//Stop it!
		SceneTable["mp_coop_lobbycoop_hub_track0201"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt01.vcd"),postdelay=0.00,next="mp_coop_lobbycoop_hub_track0202",char="glados",predelay=2.0}
		//What if you froze like that?
		SceneTable["mp_coop_lobbycoop_hub_track0202"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt02.vcd"),postdelay=0.00,next="mp_coop_lobbycoop_hub_track0203",char="glados"}
		//There must be something wrong with the assembly machine.
		SceneTable["mp_coop_lobbycoop_hub_track0203"] <- {vcd=CreateSceneEntity("scenes/npc/glados/anti_taunt05.vcd"),postdelay=0.75,next="mp_coop_lobbycoop_hub_track0204",char="glados"}
		//Well, let's do some tests and see what happens.
		SceneTable["mp_coop_lobbycoop_hub_track0204"] <- {vcd=CreateSceneEntity("scenes/npc/glados/botcoop_artifactone_hub08.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_hub_track02death
		//I know you like to think the reassembly machine is at your beck and call, but he has a life you know.  He's not your slave.
		SceneTable["mp_coop_lobbycoop_hub_track02death00"] <- {vcd=CreateSceneEntity("scenes/npc/glados/mp_coop_rat_mazedeath04.vcd"),postdelay=0.00,next=null,char="glados"}
	//coop_hub_track03
		//I don't know what you think you are doing, but I don't like it.  I want you to stop.
		SceneTable["mp_coop_lobbycoop_hub_track0301"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track09.vcd"),postdelay=0.00,next="mp_coop_lobbycoop_hub_track0302",char="glados",predelay=2.0}
		//Maybe I shouldn't send you outside of the official testing courses, you are picking up some bad human traits.
		SceneTable["mp_coop_lobbycoop_hub_track0302"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track10.vcd"),postdelay=0.00,next="mp_coop_lobbycoop_hub_track0303",char="glados"}
		//And trust me, humans only have one good trait.
		SceneTable["mp_coop_lobbycoop_hub_track0303"] <- {vcd=CreateSceneEntity("scenes/npc/glados/coop_hub_track11.vcd"),postdelay=0.00,next=null,char="glados"}
//mp_coop_lobby2                          

//SceneTableLookup
	SceneTableLookup <- {}
	SceneTableLookup[8] <- "mp_coop_startBlueFirstToEnd01"
	SceneTableLookup[1] <- "mp_coop_startBlueGetsGunFirst01"
	SceneTableLookup[3] <- "mp_coop_startBlueGetsGunSecond01"
	SceneTableLookup[5] <- "mp_coop_startBlueInterruptsRelaxationVault01"
	SceneTableLookup[1006] <- "mp_coop_startcoop_boxcalibration00"
	SceneTableLookup[1004] <- "mp_coop_startcoop_buttoncallibrationblue00"
	SceneTableLookup[1005] <- "mp_coop_startcoop_buttoncallibrationorange00"
	SceneTableLookup[1007] <- "mp_coop_startcoop_callibrationcomplete100"
	SceneTableLookup[32] <- "mp_coop_startcoop_ping_blue_success00"
	SceneTableLookup[30] <- "mp_coop_startcoop_ping_intro_animal00"
	SceneTableLookup[33] <- "mp_coop_startcoop_ping_orange_start01"
	SceneTableLookup[34] <- "mp_coop_startcoop_ping_orange_success02"
	SceneTableLookup[27] <- "mp_coop_startcoop_portal_ping_intro00"
	SceneTableLookup[1000] <- "mp_coop_startcoop_pregun_pingnag1blue00"
	SceneTableLookup[1014] <- "mp_coop_startcoop_pregun_pingnag1orange00"
	SceneTableLookup[1001] <- "mp_coop_startcoop_pregun_pingnag2blue00"
	SceneTableLookup[1015] <- "mp_coop_startcoop_pregun_pingnag2orange00"
	SceneTableLookup[50] <- "mp_coop_startcoop_results_1_0100"
	SceneTableLookup[1023] <- "mp_coop_startcoop_startboxcatch00"
	SceneTableLookup[1002] <- "mp_coop_startcoop_starttwoportals00"
	SceneTableLookup[1084] <- "mp_coop_startmp_coop_startdeath0100"
	SceneTableLookup[1085] <- "mp_coop_startmp_coop_startdeath0200"
	SceneTableLookup[1086] <- "mp_coop_startmp_coop_startdeath0300"
	SceneTableLookup[1087] <- "mp_coop_startmp_coop_startdeath0400"
	SceneTableLookup[1088] <- "mp_coop_startmp_coop_startdeath0500"
	SceneTableLookup[1064] <- "mp_coop_startmp_coop_startposttaunt01"
	SceneTableLookup[7] <- "mp_coop_startOneBlah01"
	SceneTableLookup[9] <- "mp_coop_startOrangeFirstToEnd01"
	SceneTableLookup[2] <- "mp_coop_startOrangeGetsGunFirst01"
	SceneTableLookup[4] <- "mp_coop_startOrangeGetsGunSecond01"
	SceneTableLookup[6] <- "mp_coop_startOrangeInterruptsRelaxationVault01"
	SceneTableLookup[0] <- "mp_coop_startRelaxationVaultIntro00"
	SceneTableLookup[11] <- "mp_coop_startTTT2GO101"
	SceneTableLookup[12] <- "mp_coop_startTTT2GO201"
	SceneTableLookup[10] <- "mp_coop_startTTT2Intro01"
	SceneTableLookup[1012] <- "mp_coop_doorscoop_score_blue0501"
	SceneTableLookup[1013] <- "mp_coop_doorscoop_score_orange0501"
	SceneTableLookup[1011] <- "mp_coop_doorsmo_coop_doorsend00"
	SceneTableLookup[54] <- "mp_coop_doorsmp_coop_doorsstart01"
	SceneTableLookup[18] <- "mp_coop_race_2EndLevel0701"
	SceneTableLookup[1022] <- "mp_coop_race_2mp_coop_race_2start01"
	SceneTableLookup[1016] <- "mp_coop_laser_2coop_laser_2end00"
	SceneTableLookup[1024] <- "mp_coop_laser_2coop_score_blue0301"
	SceneTableLookup[1026] <- "mp_coop_laser_2coop_score_blue0801"
	SceneTableLookup[1025] <- "mp_coop_laser_2coop_score_orange0301"
	SceneTableLookup[1027] <- "mp_coop_laser_2coop_score_orange0801"
	SceneTableLookup[15] <- "mp_coop_laser_2EndLevel0401"
	SceneTableLookup[1028] <- "mp_coop_laser_2mp_coop_laserkill01"
	SceneTableLookup[1065] <- "mp_coop_laser_2mp_coop_laser_2taunt01"
	SceneTableLookup[1038] <- "mp_coop_rat_mazemp_coop_blue_penalized_401"
	SceneTableLookup[1036] <- "mp_coop_rat_mazemp_coop_laser_2endblue01"
	SceneTableLookup[1037] <- "mp_coop_rat_mazemp_coop_laser_2endorange01"
	SceneTableLookup[1039] <- "mp_coop_rat_mazemp_coop_orange_penalized_401"
	SceneTableLookup[1043] <- "mp_coop_rat_mazemp_coop_rat_mazebluecrush00"
	SceneTableLookup[1045] <- "mp_coop_rat_mazemp_coop_rat_mazebluecrush200"
	SceneTableLookup[1047] <- "mp_coop_rat_mazemp_coop_rat_mazebluecrush300"
	SceneTableLookup[1044] <- "mp_coop_rat_mazemp_coop_rat_mazeorangecrush00"
	SceneTableLookup[1046] <- "mp_coop_rat_mazemp_coop_rat_mazeorangecrush200"
	SceneTableLookup[1048] <- "mp_coop_rat_mazemp_coop_rat_mazeorangecrush300"
	SceneTableLookup[1017] <- "mp_coop_rat_mazemp_coop_rat_mazestart00"
	SceneTableLookup[1040] <- "mp_coop_laser_crushermp_coop_laser_crusherblue00"
	SceneTableLookup[1042] <- "mp_coop_laser_crushermp_coop_laser_crusherboth00"
	SceneTableLookup[1041] <- "mp_coop_laser_crushermp_coop_laser_crusherorange01"
	SceneTableLookup[1018] <- "mp_coop_laser_crushermp_coop_laser_crusherstartblue01"
	SceneTableLookup[1019] <- "mp_coop_laser_crushermp_coop_laser_crusherstartorange01"
	SceneTableLookup[1009] <- "mp_coop_teambtsmp_coop_radarroomend00"
	SceneTableLookup[1021] <- "mp_coop_teambtsmp_coop_teambtsstart01"
	SceneTableLookup[1100] <- "mp_coop_teambtsmp_coop_teambtsstoptaunt1b00"
	SceneTableLookup[1101] <- "mp_coop_teambtsmp_coop_teambtsstoptaunt1o00"
	SceneTableLookup[1102] <- "mp_coop_teambtsmp_coop_teambtsstoptaunt201"
	SceneTableLookup[1103] <- "mp_coop_teambtsmp_coop_teambtsstoptaunt3b00"
	SceneTableLookup[1104] <- "mp_coop_teambtsmp_coop_teambtsstoptaunt3o00"
	SceneTableLookup[1105] <- "mp_coop_teambtsmp_coop_teambtsstoptaunt400"
	SceneTableLookup[1106] <- "mp_coop_teambtsmp_coop_teambtsstoptaunt501"
	SceneTableLookup[1030] <- "mp_coop_fling_3mp_coop_fling_3end01"
	SceneTableLookup[1029] <- "mp_coop_fling_3mp_coop_fling_3start01"
	SceneTableLookup[1032] <- "mp_coop_infinifling_trainmp_coop_infinifling_trainend01"
	SceneTableLookup[1049] <- "mp_coop_infinifling_trainmp_coop_infinifling_trainenddeath00"
	SceneTableLookup[1050] <- "mp_coop_infinifling_trainmp_coop_infinifling_trainendlife00"
	SceneTableLookup[1031] <- "mp_coop_infinifling_trainmp_coop_infinifling_trainstart01"
	SceneTableLookup[1034] <- "mp_coop_come_alongmp_coop_come_alongend01"
	SceneTableLookup[1056] <- "mp_coop_come_alongmp_coop_come_alongstart01"
	SceneTableLookup[1051] <- "mp_coop_catapult_1mp_coop_catapult_1end01"
	SceneTableLookup[1057] <- "mp_coop_catapult_1mp_coop_catapult_1start01"
	SceneTableLookup[1052] <- "mp_coop_multifling_1mp_coop_multifling_1end01"
	SceneTableLookup[1058] <- "mp_coop_multifling_1mp_coop_multifling_1start01"
	SceneTableLookup[1053] <- "mp_coop_fling_crushersmp_coop_fling_crushersend00"
	SceneTableLookup[1059] <- "mp_coop_fling_crushersmp_coop_fling_crushersstart01"
	SceneTableLookup[1055] <- "mp_coop_fanmp_coop_fanend01"
	SceneTableLookup[1054] <- "mp_coop_fanmp_coop_fanstart01"
	SceneTableLookup[1082] <- "mp_coop_wall_intromp_coop_wall_introend01"
	SceneTableLookup[1063] <- "mp_coop_wall_intromp_coop_wall_introstart01"
	SceneTableLookup[19] <- "mp_coop_wall_2EndLevel0801"
	SceneTableLookup[1083] <- "mp_coop_wall_2mp_coop_wall_2start01"
	SceneTableLookup[26] <- "mp_coop_catapult_wall_introCackle01"
	SceneTableLookup[25] <- "mp_coop_catapult_wall_introCatchBall01"
	SceneTableLookup[23] <- "mp_coop_catapult_wall_introEndLevel12B01"
	SceneTableLookup[24] <- "mp_coop_catapult_wall_introEndLevel12O01"
	SceneTableLookup[1097] <- "mp_coop_catapult_wall_introfacepalmreply01"
	SceneTableLookup[16] <- "mp_coop_wall_blockEndLevel0501"
	SceneTableLookup[1107] <- "mp_coop_turret_wallsmp_coop_turret_wallsstart01"
	SceneTableLookup[1061] <- "mp_coop_wall_5mp_coop_wall_5end02"
	SceneTableLookup[1060] <- "mp_coop_wall_5mp_coop_wall_5start01"
	SceneTableLookup[1098] <- "mp_coop_wall_5teamhugreply00"
	SceneTableLookup[1093] <- "mp_coop_tbeam_redirectmp_coop_tbeam_redirectbbehind00"
	SceneTableLookup[1092] <- "mp_coop_tbeam_redirectmp_coop_tbeam_redirectobehind00"
	SceneTableLookup[1068] <- "mp_coop_tbeam_redirectmp_coop_tbeam_redirectstart00"
	SceneTableLookup[1072] <- "mp_coop_tbeam_drillmp_coop_tbeam_drillendb01"
	SceneTableLookup[1071] <- "mp_coop_tbeam_drillmp_coop_tbeam_drillendo01"
	SceneTableLookup[1070] <- "mp_coop_tbeam_drillmp_coop_tbeam_drillstartb00"
	SceneTableLookup[1069] <- "mp_coop_tbeam_drillmp_coop_tbeam_drillstarto00"
	SceneTableLookup[1073] <- "mp_coop_tbeam_catch_grind_1mp_coop_tbeam_catch_grind_1start01"
	SceneTableLookup[1099] <- "mp_coop_tbeam_catch_grind_1trickfirereply00"
	SceneTableLookup[1080] <- "mp_coop_tbeam_laser_1mp_coop_tbeam_laser_1startb01"
	SceneTableLookup[1081] <- "mp_coop_tbeam_laser_1mp_coop_tbeam_laser_1starto01"
	SceneTableLookup[1066] <- "mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whisperb01"
	SceneTableLookup[1067] <- "mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2 whispero01"
	SceneTableLookup[1091] <- "mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2startb01"
	SceneTableLookup[1090] <- "mp_coop_tbeam_polarity2mp_coop_tbeam_polarity2starto01"
	SceneTableLookup[1094] <- "mp_coop_tbeam_endmp_coop_tbeam_endend01"
	SceneTableLookup[1020] <- "mp_coop_lobbycoop_hub_track0101"
	SceneTableLookup[1095] <- "mp_coop_lobbycoop_hub_track0201"
	SceneTableLookup[1096] <- "mp_coop_lobbycoop_hub_track02death00"
	SceneTableLookup[1062] <- "mp_coop_lobbycoop_hub_track0301"

//MapBspConversion
	MapBspConversion <- {}
