#include "cbase.h"


static unsigned char g_Script_spawn_helper[] = {
	"//=========================================================\n"
	"// An spawner on the server is getting ready to\n"
	"// prespawn an entity. It calls this function, sending us\n"
	"// the entity that it's preparing to spawn. \n"
	"//=========================================================\n"
	"\n"
	"function __ExecutePreSpawn(entity)\n"
	"{\n"
	"	__EntityMakerResult <-{}\n"
	"	if (\"PreSpawnInstance\" in this)\n"
	"	{\n"
	"		local overrides = PreSpawnInstance(entity.GetClassname(), entity.GetName());\n"
	"		local type = typeof(overrides);\n"
	"		if (type == \"table\")\n"
	"		{\n"
	"			foreach(key, value in overrides)\n"
	"			{\n"
	"				switch (typeof(value))\n"
	"				{\n"
	"				case \"string\":\n"
	"				{\n"
	"					entity.__KeyValueFromString(key, value);\n"
	"					break;\n"
	"				}\n"
	"				case \"integer\":\n"
	"				{\n"
	"					entity.__KeyValueFromInt(key, value);\n"
	"					break;\n"
	"				}\n"
	"				case \"float\":\n"
	"				case \"bool\":\n"
	"				{\n"
	"					entity.__KeyValueFromFloat(key, value.tofloat());\n"
	"					break;\n"
	"				}\n"
	"\n"
	"				case \"Vector\":\n"
	"				{\n"
	"					entity.__KeyValueFromVector(key, value);\n"
	"					break\n"
	"				}\n"
	"\n"
	"				default:\n"
	"				{\n"
	"					printl(\"Cannot use \" + typeof(value) + \" as a key\");\n"
	"				}\n"
	"			}\n"
	"		}\n"
	"	}\n"
	"\n"
	"			if (type == \"bool\")\n"
	"			{\n"
	"				return overrides;\n"
	"			}\n"
	"		}\n"
	"	};\n"
	"\n"
	"	function __FinishSpawn()\n"
	"	{\n"
	"		__EntityMakerResult <-null; \n"
	"	}\n"
	"\n"
};